from typing import Iterator, Optional, Tuple, Union

# ─── Exceptions ───────────────────────────────────────────────────────────────

class CodaException(Exception): ...

class CodaParseError(CodaException):
	code: int
	line: int
	col: int
	offset: int

# ─── Base ─────────────────────────────────────────────────────────────────────

class CodaNode:
	_doc: Optional["CodaDoc"]
	_node_id: Optional[int]
	@property
	def comment(self) -> str: ...
	@comment.setter
	def comment(self, value: str) -> None: ...
	def is_container(self) -> bool: ...
	def serialize(self, indent: str = "\t") -> str: ...
	def as_string(self) -> "CodaString": ...
	def as_block(self) -> "CodaBlock": ...
	def as_array(self) -> "CodaArray": ...
	def as_table(self) -> "CodaTable": ...
	def as_keyed_table(self) -> "CodaKeyedTable": ...

# ─── CodaString ───────────────────────────────────────────────────────────────

class CodaString(CodaNode):
	def __init__(self, value_or_doc: "Union[str, CodaDoc]" = "", value: str = "") -> None: ...
	@property
	def value(self) -> str: ...
	@value.setter
	def value(self, v: str) -> None: ...
	def __str__(self) -> str: ...
	def __eq__(self, other: object) -> bool: ...

# ─── CodaRow ──────────────────────────────────────────────────────────────────

class CodaRow(CodaNode):
	def __init__(self, doc: "Optional[CodaDoc]" = None) -> None: ...
	# comment uses its own API
	@property
	def comment(self) -> str: ...
	@comment.setter
	def comment(self, value: str) -> None: ...
	def __getitem__(self, col: str) -> str: ...
	def __setitem__(self, col: str, value: str) -> None: ...
	def __delitem__(self, col: str) -> None: ...
	def __iter__(self) -> Iterator[Tuple[str, str]]: ...
	def __len__(self) -> int: ...
	def __contains__(self, col: str) -> bool: ...
	def get(self, col: str, default: Optional[str] = None) -> Optional[str]: ...

# ─── CodaBlock ────────────────────────────────────────────────────────────────

_AnyNode = Union[CodaString, "CodaBlock", "CodaArray", "CodaTable", "CodaKeyedTable"]

class CodaBlock(CodaNode):
	def __init__(self, doc: "Optional[CodaDoc]" = None) -> None: ...
	def insert(self, key: str, value: _AnyNode) -> _AnyNode: ...
	def __setitem__(self, key: str, value: _AnyNode) -> None: ...
	def __getitem__(self, key: str) -> CodaNode: ...
	def __delitem__(self, key: str) -> None: ...
	def __iter__(self) -> Iterator[Tuple[str, CodaNode]]: ...
	def __len__(self) -> int: ...
	def __contains__(self, key: str) -> bool: ...
	def get_or_insert(self, key: str) -> CodaNode: ...
	def order(self) -> None: ...
	def order_weighted(self, weights: list[tuple[str, float]]) -> None: ...

# ─── CodaArray ────────────────────────────────────────────────────────────────

class CodaArray(CodaNode):
	def __init__(self, doc: "Optional[CodaDoc]" = None) -> None: ...
	@property
	def header_comment(self) -> str: ...
	@header_comment.setter
	def header_comment(self, value: str) -> None: ...
	def append(self, value: _AnyNode) -> _AnyNode: ...
	def __getitem__(self, idx: int) -> CodaNode: ...
	def __setitem__(self, idx: int, value: _AnyNode) -> None: ...
	def __delitem__(self, idx: int) -> None: ...
	def __iter__(self) -> Iterator[CodaNode]: ...
	def __len__(self) -> int: ...

# ─── CodaTable ────────────────────────────────────────────────────────────────

class CodaTable(CodaNode):
	def __init__(self, doc_or_columns: "Union[CodaDoc, list[str], None]" = None,
	             columns: "list[str]" = ...) -> None: ...
	@property
	def header_comment(self) -> str: ...
	@header_comment.setter
	def header_comment(self, value: str) -> None: ...
	def columns(self) -> list[str]: ...
	def append_col(self, name: str) -> "CodaTable": ...
	def append(self, row: CodaRow) -> "CodaTable": ...
	def __getitem__(self, idx: int) -> CodaRow: ...
	def __setitem__(self, idx: int, row: CodaRow) -> None: ...
	def __delitem__(self, idx: int) -> None: ...
	def __iter__(self) -> Iterator[CodaRow]: ...
	def __len__(self) -> int: ...

# ─── CodaKeyedTable ───────────────────────────────────────────────────────────

class CodaKeyedTable(CodaNode):
	def __init__(self, doc_or_columns: "Union[CodaDoc, list[str], None]" = None,
	             columns: "list[str]" = ...) -> None: ...
	@property
	def header_comment(self) -> str: ...
	@header_comment.setter
	def header_comment(self, value: str) -> None: ...
	def columns(self) -> list[str]: ...
	def append_col(self, name: str) -> "CodaKeyedTable": ...
	def insert(self, key: str, row: CodaRow) -> CodaRow: ...
	def __setitem__(self, key: str, row: CodaRow) -> None: ...
	def __getitem__(self, key: str) -> CodaRow: ...
	def __delitem__(self, key: str) -> None: ...
	def __iter__(self) -> Iterator[Tuple[str, CodaRow]]: ...
	def __len__(self) -> int: ...
	def __contains__(self, key: str) -> bool: ...
	def order(self) -> None: ...
	def order_weighted(self, weights: list[tuple[str, float]]) -> None: ...

# ─── CodaDoc ──────────────────────────────────────────────────────────────────

class CodaDoc:
	def __init__(self, ptr: int) -> None: ...

	# ── Lifecycle ─────────────────────────────────────────────────────────────
	@classmethod
	def parse(cls, text: str, filename: Optional[str] = None) -> "CodaDoc": ...
	@classmethod
	def parse_file(cls, path: str) -> "CodaDoc": ...
	@classmethod
	def new(cls) -> "CodaDoc": ...
	def __enter__(self) -> "CodaDoc": ...
	def __exit__(self, *_: object) -> bool: ...
	def free(self) -> None: ...

	# ── Root access ───────────────────────────────────────────────────────────
	def root(self) -> CodaBlock: ...

	# ── Serialisation ─────────────────────────────────────────────────────────
	def serialize(self, indent: str = "\t") -> str: ...
	def save(self, path: str, indent: str = "\t") -> None: ...
	def order(self) -> None: ...
	def order_weighted(self, weights: list[tuple[str, float]]) -> None: ...
	def order_weighted_and_serialize(self, weights: list[tuple[str, float]],
	                                 indent: str = "\t") -> str: ...

# ─── Module-level ─────────────────────────────────────────────────────────────

def get_abi_version() -> int: ...
def run_catalog_tests(catalog_path: str) -> None: ...

__all__: list[str]
