from typing import Iterator, Optional, Tuple

class CodaException(Exception):
	pass

class CodaParseError(CodaException):
	code: int
	line: int
	col: int
	offset: int

class Coda:
	def __init__(self, doc: "CodaDoc", node_id: int) -> None: ...
	@property
	def kind(self) -> int: ...
	def asString(self) -> str: ...
	def asArray(self) -> Iterator["Coda"]: ...
	def asBlock(self) -> Iterator[Tuple[str, "Coda"]]: ...
	def asTable(self) -> Iterator[Tuple[str, "Coda"]]: ...
	def __getitem__(self, key: str) -> "Coda": ...
	def __setitem__(self, key: str, value: str) -> None: ...
	def get(self, key: str, default: Optional[str] = None) -> Optional[str]: ...
	def get_or_insert(self, key: str) -> "Coda": ...
	@property
	def comment(self) -> str: ...
	@comment.setter
	def comment(self, value: str) -> None: ...
	@property
	def header_comment(self) -> str: ...
	@header_comment.setter
	def header_comment(self, value: str): ...

class CodaDoc:
	def __init__(self, ptr: int) -> None: ...
	@classmethod
	def parse(cls, text: str, filename: Optional[str] = None) -> "CodaDoc": ...
	@classmethod
	def parse_file(cls, path: str) -> "CodaDoc": ...
	@classmethod
	def new(cls) -> "CodaDoc": ...
	def __enter__(self) -> "CodaDoc": ...
	def __exit__(self, exc_type, exc_val, exc_tb) -> bool: ...
	def free(self) -> None: ...
	def root(self) -> Coda: ...
	def __getitem__(self, key: str) -> Coda: ...
	def __setitem__(self, key: str, value: str) -> None: ...
	def serialize(self, indent: str = "\t") -> str: ...
	def save(self, path: str, indent: str = "\t") -> None: ...
	def order(self) -> None: ...
	def order_weighted_and_serialize(self, weights: list[tuple[str, float]]) -> str: ...

def get_abi_version() -> int: ...
def run_catalog_tests(catalog_path: str) -> None: ...

__all__: list[str]
