from typing import Iterator, Optional, Tuple, Union

# ─── Exceptions ───────────────────────────────────────────────────────────────

class Error(Exception): ...

class ParseError(Error):
	code: int
	line: int
	col: int
	offset: int

# ─── Base ─────────────────────────────────────────────────────────────────────

class Node:
	_doc: Optional["Doc"]
	_node_id: Optional[int]
	@property
	def comment(self) -> str: ...
	@comment.setter
	def comment(self, value: str) -> None: ...
	def is_container(self) -> bool: ...
	def serialize(self, indent: str = "\t") -> str: ...
	def as_string(self) -> "Node": ...
	def as_block(self) -> "Block": ...
	def as_array(self) -> "Array": ...
	def as_table(self) -> "Table": ...
	def as_keyed_table(self) -> "KeyedTable": ...

# ─── Row ──────────────────────────────────────────────────────────────────

class Row(Node):
	def __init__(self) -> None: ...
	# comment uses its own API
	@property
	def comment(self) -> str: ...
	@comment.setter
	def comment(self, value: str) -> None: ...
	def __getitem__(self, col: str) -> str: ...
	def __setitem__(self, col: str, value: str) -> None: ...
	def __delitem__(self, col: str) -> None: ...
	def __iter__(self) -> Iterator[Tuple[str, str]]: ...
	def __len__(self) -> int: ...
	def __contains__(self, col: str) -> bool: ...
	def get(self, col: str, default: Optional[str] = None) -> Optional[str]: ...

# ─── Block ────────────────────────────────────────────────────────────────

_AnyNode = Union[str, "Block", "Array", "Table", "KeyedTable"]

class Block(Node):
	def __init__(self) -> None: ...
	def insert(self, key: str, value: _AnyNode) -> "Block": ...
	def __setitem__(self, key: str, value: _AnyNode) -> None: ...
	def __getitem__(self, key: str) -> Node: ...
	def __delitem__(self, key: str) -> None: ...
	def __iter__(self) -> Iterator[Tuple[str, Node]]: ...
	def __len__(self) -> int: ...
	def __contains__(self, key: str) -> bool: ...
	def get_or_insert(self, key: str) -> Node: ...
	def order(self) -> None: ...
	def order_weighted(self, weights: list[tuple[str, float]]) -> None: ...

# ─── Array ────────────────────────────────────────────────────────────────

class Array(Node):
	def __init__(self) -> None: ...
	@property
	def header_comment(self) -> str: ...
	@header_comment.setter
	def header_comment(self, value: str) -> None: ...
	def append(self, value: _AnyNode) -> _AnyNode: ...
	def __getitem__(self, idx: int) -> Node: ...
	def __setitem__(self, idx: int, value: _AnyNode) -> None: ...
	def __delitem__(self, idx: int) -> None: ...
	def __iter__(self) -> Iterator[Node]: ...
	def __len__(self) -> int: ...

# ─── Table ────────────────────────────────────────────────────────────────

class Table(Node):
	def __init__(self, columns: "list[str]" = ...) -> None: ...
	@property
	def header_comment(self) -> str: ...
	@header_comment.setter
	def header_comment(self, value: str) -> None: ...
	def columns(self) -> list[str]: ...
	def append_col(self, name: str) -> "Table": ...
	def append(self, row: Row) -> "Table": ...
	def __getitem__(self, idx: int) -> Row: ...
	def __setitem__(self, idx: int, row: Row) -> None: ...
	def __delitem__(self, idx: int) -> None: ...
	def __iter__(self) -> Iterator[Row]: ...
	def __len__(self) -> int: ...

# ─── KeyedTable ───────────────────────────────────────────────────────────

class KeyedTable(Node):
	def __init__(self, columns: "list[str]" = ...) -> None: ...
	@property
	def header_comment(self) -> str: ...
	@header_comment.setter
	def header_comment(self, value: str) -> None: ...
	def columns(self) -> list[str]: ...
	def append_col(self, name: str) -> "KeyedTable": ...
	def insert(self, key: str, row: Row) -> Row: ...
	def __setitem__(self, key: str, row: Row) -> None: ...
	def __getitem__(self, key: str) -> Row: ...
	def __delitem__(self, key: str) -> None: ...
	def __iter__(self) -> Iterator[Tuple[str, Row]]: ...
	def __len__(self) -> int: ...
	def __contains__(self, key: str) -> bool: ...
	def order(self) -> None: ...
	def order_weighted(self, weights: list[tuple[str, float]]) -> None: ...

# ─── Doc ──────────────────────────────────────────────────────────────────

class Doc:
	def __init__(self, ptr: int) -> None: ...

	# ── Lifecycle ─────────────────────────────────────────────────────────────
	@classmethod
	def parse(cls, text: str, filename: Optional[str] = None) -> "Doc": ...
	@classmethod
	def parse_file(cls, path: str) -> "Doc": ...
	@classmethod
	def new(cls) -> "Doc": ...
	def __enter__(self) -> "Doc": ...
	def __exit__(self, *_: object) -> bool: ...
	def free(self) -> None: ...

	# ── Root access ───────────────────────────────────────────────────────────
	def root(self) -> Block: ...

	# ── Serialisation ─────────────────────────────────────────────────────────
	def serialize(self, indent: str = "\t") -> str: ...
	def save(self, path: str, indent: str = "\t") -> None: ...
	def order(self) -> None: ...
	def order_weighted(self, weights: list[tuple[str, float]]) -> None: ...
	def order_weighted_and_serialize(self, weights: list[tuple[str, float]],
	                                 indent: str = "\t") -> str: ...

# ─── Module-level ─────────────────────────────────────────────────────────────

def get_abi_version() -> int: ...

__all__: list[str]
