name: CI

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:

  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install devbox + packages
        uses: jetify-com/devbox-install-action@v0.15.0

      - name: Run tests
        run: devbox run -- just test
